### ISSUE TITLE
Adding Island Names

### ISSUE THREAD

**Issue by JScythe9998** [Sparen/StripMapGen#23]
Hello, 
I was able to add a river to my strip map like in Test 2 - Line 13 and Test 3 - Line 14. This wasn't addressed in your instructions, but I was wondering if you could tell me how to specify the names of the lands on both sides of the river preferably diagonally and on the top left and right of the river. I will provide a picture. I circled the places where I'd like the names to be. Thank you for your time. 
![Island](https://github.com/user-attachments/assets/f2d0438e-07df-4771-b92f-2592202274c2)

**Comment by Sparen** [comment]
To be blunt, this tool was not made with this case in mind - my recommendations fall into three categories:

- Add the text horizontally below the lines and stations instead of above
- Do what you currently plan, but with additional buffer 'fake' stations. It's not perfect but you can use an offset on one of them to shift the text upwards, using the 'diagonal by default'. However, since it will look like station name text, you may need to adjust some settings for that station type
- Use a custom approach where you manually add SVG. This option is the most flexible but the current implementation uses fixed coordinates, so if you add/remove stations and the river automatically shifts its position, you will need to move the text on your end since it will not be automatic.

**Comment by JScythe9998** [comment]
I figured out a solution. I used  `maincustomsvgbg` to put the island names and position them on both sides of the river like this:
 `"maincustomsvgbg": "<text x='800' y='330' fill='#000000' text-anchor='start' dominant-baseline='central'>Island1</text>,<text x='875' y='330' fill='#000000' text-anchor='start' dominant-baseline='central'>Island2</text>",`
Thanks for all your help.
